"use client";

import { Landmark, MessageCircleMore, Plus, Trash2 } from "lucide-react";
import { AdminFeedback } from "@/components/admin/admin-feedback";
import { SectionCard, TextControl } from "./settings-form-controls";
import { SettingsSectionHeader } from "./settings-section-header";
import { SettingsSectionSkeleton } from "./settings-section-skeleton";
import { addPhoneContact, buildContactSettingsJson, makeContactSettingsSnapshot, mapContactSettingsResponse, removePhoneContact, updatePhoneContact } from "./settings-helpers";
import { validateContactSettingsDraft } from "./settings-validation";
import { useAdminSettingsSection } from "./use-admin-settings-section";

export function ContactSettingsPage() {
  const state = useAdminSettingsSection({ section: "contact", mapResponse: mapContactSettingsResponse, makeSnapshot: makeContactSettingsSnapshot, buildRequest: (draft) => ({ body: buildContactSettingsJson(draft), headers: { "Content-Type": "application/json" } }), validate: validateContactSettingsDraft });
  const { draft } = state;
  return <div className="grid gap-5">
    <SettingsSectionHeader title="ติดต่อและชำระเงิน" description="จัดการช่องทางติดต่อและข้อมูลบัญชีธนาคารที่ใช้จริงบนหน้าเว็บไซต์" hasUnsavedChanges={state.hasUnsavedChanges} isSaving={state.isSaving} onSave={state.save} />
    <AdminFeedback errors={state.errors} notice={state.notice} warnings={state.warnings} />
    {state.isLoading ? <SettingsSectionSkeleton /> : draft ? <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
      <div className="grid gap-5"><SectionCard description="ข้อมูลบัญชีที่แสดงให้ลูกค้าใช้ชำระเงิน" icon={<Landmark aria-hidden="true" className="size-5" />} id="bank" title="ข้อมูลชำระเงิน"><div className="grid gap-4 lg:grid-cols-3"><TextControl id="bankAccountName" label="ชื่อบัญชี" value={draft.bankAccountName} onChange={(bankAccountName) => state.updateDraft({ bankAccountName })} /><TextControl id="bankName" label="ชื่อธนาคาร" value={draft.bankName} onChange={(bankName) => state.updateDraft({ bankName })} /><TextControl id="bankAccountNumber" label="เลขบัญชี" value={draft.bankAccountNumber} onChange={(bankAccountNumber) => state.updateDraft({ bankAccountNumber })} /></div></SectionCard>
      <SectionCard description="เบอร์โทร Messenger และ LINE ที่แสดงบนหน้าเว็บไซต์" icon={<MessageCircleMore aria-hidden="true" className="size-5" />} id="contact" title="ช่องทางติดต่อ"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">เบอร์โทรติดต่อ</p><button className="inline-flex h-10 items-center gap-2 rounded-md border px-3 text-sm font-semibold" type="button" onClick={() => state.updateDraft({ phoneContacts: addPhoneContact(draft.phoneContacts) })}><Plus className="size-4" />เพิ่มเบอร์โทร</button></div>{draft.phoneContacts.map((contact, index) => <div className="rounded-lg border border-[var(--site-border)] bg-[var(--site-surface-soft)] p-4" key={index}><div className="mb-3 flex justify-between"><p className="font-semibold">ผู้ติดต่อคนที่ {index + 1}</p>{draft.phoneContacts.length > 1 ? <button aria-label={`ลบผู้ติดต่อคนที่ ${index + 1}`} type="button" onClick={() => state.updateDraft({ phoneContacts: removePhoneContact(draft.phoneContacts, index) })}><Trash2 className="size-4" /></button> : null}</div><div className="grid gap-4 lg:grid-cols-3"><TextControl id={`phoneContactName-${index}`} label="ชื่อผู้ติดต่อ" value={contact.name} onChange={(name) => state.updateDraft({ phoneContacts: updatePhoneContact(draft.phoneContacts, index, { name }) })} /><TextControl id={`phoneContactPhone-${index}`} label="เบอร์โทร" inputMode="tel" value={contact.phone} onChange={(phone) => state.updateDraft({ phoneContacts: updatePhoneContact(draft.phoneContacts, index, { phone }) })} /><TextControl id={`phoneContactTime-${index}`} label="ช่วงเวลาติดต่อ" value={contact.time} onChange={(time) => state.updateDraft({ phoneContacts: updatePhoneContact(draft.phoneContacts, index, { time }) })} /></div></div>)}<div className="grid gap-4 lg:grid-cols-3"><TextControl id="messengerUrl" label="ลิงก์ Messenger" inputMode="url" value={draft.messengerUrl} onChange={(messengerUrl) => state.updateDraft({ messengerUrl })} /><TextControl id="lineId" label="LINE ID" value={draft.lineId} onChange={(lineId) => state.updateDraft({ lineId })} /><TextControl id="lineUrl" label="ลิงก์ LINE" inputMode="url" value={draft.lineUrl} onChange={(lineUrl) => state.updateDraft({ lineUrl })} /></div></SectionCard></div>
      <aside className="rounded-lg border border-[var(--site-border)] bg-[var(--site-surface)] p-5 shadow-sm"><h2 className="font-bold">สรุปข้อมูลติดต่อ</h2><dl className="mt-4 grid gap-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-[var(--site-muted)]">เบอร์โทร</dt><dd className="font-semibold">{draft.phoneContacts.filter((item) => item.name.trim() || item.phone.trim() || item.time.trim()).length} รายการ</dd></div><div className="flex justify-between gap-3"><dt className="text-[var(--site-muted)]">Messenger</dt><dd className="max-w-40 truncate font-semibold">{draft.messengerUrl}</dd></div><div className="flex justify-between gap-3"><dt className="text-[var(--site-muted)]">LINE</dt><dd className="font-semibold">{draft.lineId}</dd></div></dl><div className="mt-5 rounded-md bg-[var(--site-primary-soft)] p-4"><Landmark className="size-5 text-[var(--site-primary)]" /><p className="mt-2 font-semibold">{draft.bankName || "ยังไม่ได้ระบุ"}</p><p className="mt-1 text-sm">{draft.bankAccountNumber}</p><p className="text-sm text-[var(--site-muted)]">{draft.bankAccountName}</p></div></aside>
    </div> : null}
  </div>;
}
