"use client";

import { Palette } from "lucide-react";
import { AdminFeedback } from "@/components/admin/admin-feedback";
import { ColorControl, SectionCard } from "./settings-form-controls";
import { buildDraftThemeStyle, buildThemeSettingsJson, makeThemeSettingsSnapshot, mapThemeSettingsResponse } from "./settings-helpers";
import { SettingsSectionHeader } from "./settings-section-header";
import { SettingsSectionSkeleton } from "./settings-section-skeleton";
import { validateThemeSettingsDraft } from "./settings-validation";
import { useAdminSettingsSection } from "./use-admin-settings-section";

export function ThemeSettingsPage() {
  const state = useAdminSettingsSection({ section: "theme", mapResponse: mapThemeSettingsResponse, makeSnapshot: makeThemeSettingsSnapshot, buildRequest: (draft) => ({ body: buildThemeSettingsJson(draft), headers: { "Content-Type": "application/json" } }), validate: validateThemeSettingsDraft });
  const { draft } = state;
  const themeStyle = draft ? buildDraftThemeStyle(draft) : undefined;
  return <div className="grid gap-5">
    <SettingsSectionHeader title="สีและธีม" description="ปรับสีหลัก ลิงก์ และข้อมูลไฮไลท์ที่ใช้ร่วมกันทั้งเว็บไซต์" hasUnsavedChanges={state.hasUnsavedChanges} isSaving={state.isSaving} onSave={state.save} />
    <AdminFeedback errors={state.errors} errorTitle="กรุณาแก้ไขก่อนบันทึก:" notice={state.notice} warnings={state.warnings} />
    {state.isLoading ? <SettingsSectionSkeleton /> : draft ? <div className="settings-preview-theme grid min-w-0 gap-5" style={themeStyle}>
      <div data-theme-color-group="primary-actions"><SectionCard description="สีสำหรับปุ่มหลักและข้อความที่ต้องการเน้น" icon={<Palette aria-hidden="true" className="size-5" />} id="theme-primary-actions" title="ปุ่มและสีเน้น"><div className="grid gap-4 lg:grid-cols-2"><ColorControl id="primaryColor" label="สีหลัก" description="ใช้กับปุ่มหลักและส่วนสำคัญ" value={draft.primaryColor} onChange={(value) => state.updateDraft({ primaryColor: value })} /><ColorControl id="accentColor" label="สีเน้น" description="ใช้เน้นข้อความหรือส่วนรอง" value={draft.accentColor} onChange={(value) => state.updateDraft({ accentColor: value })} /></div><div className="rounded-lg border border-[var(--site-border)] bg-[var(--site-surface-soft)] p-4"><button className="rounded-md bg-[var(--site-primary)] px-4 py-2 text-sm font-semibold text-[var(--site-on-primary)]" type="button">ดูบ้านพัก</button><span className="ml-3 font-semibold text-[var(--site-accent)]">สีเน้น</span></div></SectionCard></div>
      <div data-theme-color-group="header-menu"><SectionCard description="สีข้อความเมนูบนเว็บไซต์" icon={<Palette aria-hidden="true" className="size-5" />} id="theme-header-menu" title="เมนู Header"><div className="grid gap-4 lg:grid-cols-2"><ColorControl id="headerLinkColor" label="สีเมนูใน Header" description="สีข้อความลิงก์ใน Header" value={draft.headerLinkColor} onChange={(value) => state.updateDraft({ headerLinkColor: value })} /><ColorControl id="headerLinkHoverColor" label="สี Hover เมนูใน Header" description="สีลิงก์เมื่อชี้เมาส์" value={draft.headerLinkHoverColor} onChange={(value) => state.updateDraft({ headerLinkHoverColor: value })} /></div><div className="rounded-lg bg-[var(--site-primary)] p-4 text-[var(--site-on-primary)]"><p className="font-bold">Pool Villas Pattaya</p><nav aria-label="เมนู Header ตัวอย่าง" className="mt-3 flex flex-wrap gap-3 text-xs font-semibold"><span className="text-[var(--site-header-link)]">หน้าแรก</span><span className="text-[var(--site-header-link-hover)]">ค้นหาบ้านพัก (Hover)</span></nav></div></SectionCard></div>
      <div data-theme-color-group="bank-details"><SectionCard description="สีข้อความสำคัญในข้อมูลบัญชีสำหรับการโอนเงิน" icon={<Palette aria-hidden="true" className="size-5" />} id="theme-bank-details" title="ข้อมูลบัญชี"><div className="grid gap-4 lg:grid-cols-2"><ColorControl id="bankHighlightColor" label="สีไฮไลท์บัญชี" description="ใช้กับข้อมูลบัญชี" value={draft.bankHighlightColor} onChange={(value) => state.updateDraft({ bankHighlightColor: value })} /><ColorControl id="bankAccountHighlightColor" label="สีชื่อบัญชี" description="ใช้กับข้อความชื่อบัญชี" value={draft.bankAccountHighlightColor} onChange={(value) => state.updateDraft({ bankAccountHighlightColor: value })} /><ColorControl id="bankNameHighlightColor" label="สีชื่อธนาคาร" description="ใช้กับข้อความชื่อธนาคาร" value={draft.bankNameHighlightColor} onChange={(value) => state.updateDraft({ bankNameHighlightColor: value })} /><ColorControl id="bankNumberHighlightColor" label="สีเลขบัญชี" description="ใช้กับข้อความเลขบัญชี" value={draft.bankNumberHighlightColor} onChange={(value) => state.updateDraft({ bankNumberHighlightColor: value })} /></div><div className="rounded-lg border border-[var(--site-border)] bg-[var(--site-surface-soft)] p-4 text-sm">กรุณาโอนเงิน <span className="text-[var(--site-bank-highlight)]">ข้อมูลบัญชี</span> <span className="text-[var(--site-bank-account-highlight)]">ชื่อบัญชี</span> <span className="text-[var(--site-bank-name-highlight)]">ชื่อธนาคาร</span> <span className="text-[var(--site-bank-number-highlight)]">เลขบัญชี</span></div></SectionCard></div>
      <div data-theme-color-group="footer-menu"><SectionCard description="สีข้อความเมนูส่วนท้ายของเว็บไซต์" icon={<Palette aria-hidden="true" className="size-5" />} id="theme-footer-menu" title="เมนู Footer"><div className="grid gap-4 lg:grid-cols-2"><ColorControl id="footerLinkColor" label="สีเมนูใน Footer" description="สีข้อความลิงก์ใน Footer" value={draft.footerLinkColor} onChange={(value) => state.updateDraft({ footerLinkColor: value })} /><ColorControl id="footerLinkHoverColor" label="สี Hover เมนูใน Footer" description="สีลิงก์เมื่อชี้เมาส์" value={draft.footerLinkHoverColor} onChange={(value) => state.updateDraft({ footerLinkHoverColor: value })} /></div><footer className="rounded-lg bg-[var(--site-primary)] p-4 text-xs"><span className="text-[var(--site-footer-link)]">ติดต่อเรา</span><span className="ml-3 text-[var(--site-footer-link-hover)]">บทความ (Hover)</span></footer></SectionCard></div>
    </div> : null}
  </div>;
}
