export const MOCK_CALENDAR_DAYS = [
  { day: 1, state: "free" },
  { day: 2, state: "free" },
  { day: 3, state: "free" },
  { day: 4, state: "free" },
  { day: 5, state: "free" },
  { day: 6, state: "free" },
  { day: 7, state: "free" },
  { day: 8, state: "free" },
  { day: 9, state: "booked" },
  { day: 10, state: "booked" },
  { day: 11, state: "free" },
  { day: 12, state: "free" },
  { day: 13, state: "free" },
  { day: 14, state: "free" },
  { day: 15, state: "free" },
  { day: 16, state: "free" },
  { day: 17, state: "free" },
  { day: 18, state: "promo" },
  { day: 19, state: "promo" },
  { day: 20, state: "promo" },
  { day: 21, state: "promo" },
  { day: 22, state: "free" },
  { day: 23, state: "free" },
  { day: 24, state: "free" },
  { day: 25, state: "free" },
  { day: 26, state: "free" },
  { day: 27, state: "free" },
  { day: 28, state: "free" },
  { day: 29, state: "selected" },
  { day: 30, state: "selected" },
  { day: 31, state: "free" },
];

export const IMAGE_ZONE_LABELS: Record<string, string> = {
  bathroom: "ห้องน้ำ",
  bedroom: "ห้องนอน",
  cover: "รูปปก",
  inside: "ภายในบ้าน",
  kitchen: "ครัว",
  livingroom: "ห้องนั่งเล่น",
  living_room: "ห้องนั่งเล่น",
  mock: "Mock FE",
  outside: "ภายนอกบ้าน",
  parking: "ที่จอดรถ",
  pool: "สระว่ายน้ำ",
  review: "รีวิว",
  uncategorized: "ไม่ระบุหมวด",
};
