// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/components/admin/admin-auth", () => ({ readAdminAccessToken: vi.fn(async () => "token") }));
vi.mock("next/link", () => ({ default: ({ href, children, ...props }: React.ComponentProps<"a">) => <a href={href} {...props}>{children}</a> }));
import { AdminVillaReviewsPage } from "../admin-villa-reviews-page";
let root: Root, host: HTMLDivElement;
beforeEach(() => { vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT", true); vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ items: [{ id:"r1",villaId:"42",villaTitle:"Happy D Pool",rating:4,commentExcerpt:"สะอาดมาก",maskedPhone:"xxx-xxxx-6993",imageCount:2,reviewImageUrl:"https://localhost/storage/v1/object/public/villa-reviews/r1.jpg",createdAt:"2026-09-07T00:00:00Z",updatedAt:"2026-09-07T00:00:00Z" }],total:12482,page:8,pageSize:6 }),{status:200}))); host=document.createElement("div");document.body.append(host);root=createRoot(host); });
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.unstubAllGlobals();vi.restoreAllMocks()});
describe("admin review list",()=>{
 it("renders only masked data, total, table row and URL-preserving edit link",async()=>{await act(async()=>root.render(<AdminVillaReviewsPage initialQuery={{q:"happy",rating:"1",page:"8",sort:"newest"}}/>));expect(host.textContent).toContain("12,482 รีวิว");expect(host.textContent).toContain("xxx-xxxx-6993");expect(host.textContent).not.toContain("+668");const link=host.querySelector('a[href*="/admin/villa-reviews/r1"]');expect(link?.getAttribute("href")).toContain("back=");expect(link?.getAttribute("href")).toContain("page%3D8");});
 it("uses the house-code search placeholder and renders the review image",async()=>{await act(async()=>root.render(<AdminVillaReviewsPage initialQuery={{q:"happy",rating:"1",sort:"lowest"}}/>));expect((host.querySelector('input[name="q"]') as HTMLInputElement).placeholder).toBe("ค้นหารหัสบ้าน ชื่อบ้านพัก เบอร์โทร หรือข้อความ");expect((host.querySelector('select[name="rating"]') as HTMLSelectElement).value).toBe("1");expect((host.querySelector('select[name="sort"]') as HTMLSelectElement).value).toBe("lowest");expect(host.querySelector('img[alt="รูปรีวิว Happy D Pool"]')).not.toBeNull();});
 it("has a search button beside the query input and calculates a six-review page",async()=>{await act(async()=>root.render(<AdminVillaReviewsPage initialQuery={{page:"8"}}/>));expect(host.querySelector('button[type="submit"]')?.textContent).toContain("ค้นหา");expect(host.textContent).toContain("43–48 จาก 12,482 รีวิว");});
 it("does not render a clickable next link on the last page",async()=>{vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({items:[],total:6,page:1,pageSize:6}),{status:200}));await act(async()=>root.render(<AdminVillaReviewsPage initialQuery={{page:"1"}}/>));expect(host.querySelector('a[href*="page=2"]')).toBeNull();expect([...host.querySelectorAll('[aria-disabled="true"]')].some((element)=>element.textContent?.includes("ถัดไป"))).toBe(true);});
 it("groups the date filter and keeps review rows in the reference-card layout",async()=>{await act(async()=>root.render(<AdminVillaReviewsPage/>));expect(host.textContent).toContain("ช่วงวันที่ทั้งหมด");expect(host.querySelector('[data-review-list-row]')).not.toBeNull();expect(host.querySelector('select[name="villaId"]')).toBeNull();});
 it("shows an error instead of leaving the list loading when the request rejects",async()=>{vi.mocked(fetch).mockRejectedValueOnce(new Error("offline"));await act(async()=>{root.render(<AdminVillaReviewsPage/>);await Promise.resolve();await Promise.resolve();});expect(host.textContent).toContain("ไม่สามารถโหลดรีวิวได้");expect(host.textContent).not.toContain("กำลังโหลดรีวิว…");});
});
